import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//       <NextIntlClientProvider>{children}</NextIntlClientProvider>
      
//       </body>
//     </html>
//   );
// }


import { Cairo, Inter } from "next/font/google";
import "./globals.css";
import { IconSprite } from "@/components/homecomponent/icon-sprite";
import { Navbar } from "./client/landing_client";
import { getCurrentUser } from "@/lib/supabase/get-user";
import { getMyMentorApplication } from "./actions/mentor_actions";

const cairo = Cairo({ subsets: ["arabic", "latin"], weight: ["400","500","600","700","800","900"], variable: "--font-cairo" });
const inter = Inter({ subsets: ["latin"], weight: ["400","500","600","700","800"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "COCR — بنتنافس على أحسن رحلة تعلّم",
  description: "منظومة تعليمية للطلاب مبنية على Near Peer Learning: رحلة واضحة، مينتور سبقك بسنة، ومشروع تطلع بيه.",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const user = await getCurrentUser().catch(() => null);
  const displayName = (user?.user_metadata?.full_name as string | undefined) ?? user?.email ?? null;
  // بيانات المينتور مطلوبة هنا بس عشان الناف بار يعرف يورّي رابط "مينتور" —
  // نفس الدالة المستخدمة في كل صفحات المينتور، مفيش استعلام جديد
  const mentorApplication = user ? await getMyMentorApplication().catch(() => null) : null;
  const isApprovedMentor = mentorApplication?.status === "approved";

  return (
    <html lang="ar" dir="rtl" className={`${cairo.variable} ${inter.variable}`}>
      <body className="overflow-x-hidden antialiased">
        <IconSprite />
        <Navbar isAuthenticated={!!user} displayName={displayName} isApprovedMentor={isApprovedMentor} />
       <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
